
cask_args appdir: '/Applications'
tap 'caskroom/cask'

cask '1password'
cask 'android-studio'
cask 'atom'
cask 'backblaze'
cask 'dropbox'
cask 'fantastical'
cask 'google-chrome'
cask 'iterm2'
cask 'imageoptim'
cask 'java'
cask 'karabiner'
cask 'omnifocus'
cask 'qt-creator'
cask 'seil'
cask 'slack'
cask 'spectacle'

brew 'android-ndk'
brew 'apktool'
brew 'ccache'
brew 'colordiff'
brew 'coreutils'
brew 'git'
brew 'gradle'
brew 'grc'
brew 'hub'
brew 'imagemagick'
brew 'neovim'
brew 'npm'
brew 'qt'
brew 'qt5'
brew 'reattach-to-user-namespace'
brew 'the_silver_searcher'
brew 'tmux'
brew 'zsh'
