apm install linter
apm install linter-clang
apm install linter-pylint
apm install nucleus-dark-ui
apm install minimap
apm install git-plus
apm install linter-jshint
apm install pretty-json
apm install highlight-selected
apm install minimap-highlight-selected
apm install atom-terminal
